/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Message { 'id' : bigint, 'content' : string, 'sentAt' : Time }
export interface PDFEntry {
  'id' : bigint,
  'title' : string,
  'grade' : string,
  'blobId' : ExternalBlob,
  'uploadedAt' : Time,
}
export interface StudentProfile {
  'username' : string,
  'password' : string,
  'name' : string,
  'grade' : string,
  'registeredAt' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'name' : string,
  'grade' : string,
  'registeredAt' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMessage' : ActorMethod<[string], undefined>,
  'addPDF' : ActorMethod<[string, string, ExternalBlob], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMessage' : ActorMethod<[bigint], undefined>,
  'deletePDF' : ActorMethod<[bigint], undefined>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getAllPDFs' : ActorMethod<[], Array<PDFEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPDFsByGrade' : ActorMethod<[string], Array<PDFEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[string, string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginAdmin' : ActorMethod<[string, string], boolean>,
  'loginStudent' : ActorMethod<[string, string], StudentProfile>,
  'registerStudent' : ActorMethod<[string, string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePDF' : ActorMethod<[bigint, string, string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];