/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sentAt' : Time,
});
export const PDFEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'grade' : IDL.Text,
  'blobId' : ExternalBlob,
  'uploadedAt' : Time,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
  'grade' : IDL.Text,
  'registeredAt' : Time,
});
export const StudentProfile = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'grade' : IDL.Text,
  'registeredAt' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMessage' : IDL.Func([IDL.Text], [], []),
  'addPDF' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMessage' : IDL.Func([IDL.Nat], [], []),
  'deletePDF' : IDL.Func([IDL.Nat], [], []),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllPDFs' : IDL.Func([], [IDL.Vec(PDFEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPDFsByGrade' : IDL.Func([IDL.Text], [IDL.Vec(PDFEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'loginStudent' : IDL.Func([IDL.Text, IDL.Text], [StudentProfile], []),
  'registerStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePDF' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sentAt' : Time,
  });
  const PDFEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'grade' : IDL.Text,
    'blobId' : ExternalBlob,
    'uploadedAt' : Time,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'name' : IDL.Text,
    'grade' : IDL.Text,
    'registeredAt' : Time,
  });
  const StudentProfile = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'grade' : IDL.Text,
    'registeredAt' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMessage' : IDL.Func([IDL.Text], [], []),
    'addPDF' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMessage' : IDL.Func([IDL.Nat], [], []),
    'deletePDF' : IDL.Func([IDL.Nat], [], []),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllPDFs' : IDL.Func([], [IDL.Vec(PDFEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPDFsByGrade' : IDL.Func([IDL.Text], [IDL.Vec(PDFEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'loginStudent' : IDL.Func([IDL.Text, IDL.Text], [StudentProfile], []),
    'registerStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePDF' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };